name: Kya-Haal          #Project ka naam
 on: [push,workflow_dispatch]    #kaha se trigger karna hai, manually trigger ho isliye workflow_dispatch likha hai
# on:
#   push:
#     branches:
#       - main
#       - features/**
#       - workflow_dispatch

jobs:
  Test:                   #job ka naam
    runs-on: VM-Runner     #runner ka kaam
    steps:
      # - name: Get Code     #local se runner me code copy kara raha hu
        # run: |
        #   echo "Cloning Repo.."
        #   echo "${{toJson(github)}}"         #Expression Context me code dalenge
        #   git clone https://github.com/${{github.repository}}.git
       
       - name: Get Code 
         uses: actions/checkout@v5                          #Local se vm me code copy ho jayega
 
       - name: Install Node.js v20
         uses: actions/setup-node@v4                         #Node v20 install hoga
         with:
           node-version: 20

       - name: Print Node Version                            #Node ka version check karenge. Aapke Node install karna hoga aapke self Hosted runner me.
         run: node -v

       - name: Install Dependencies
         run: npm install                                   # "npm ci" bhi use kar skate hai automated env ke liye
        
       - name: Run Test Case                                # Run test Case from Package.json
         run: npm run test
  
  Deploy:
    needs: Test                                             #Test job complete hone ke baad ye Deploy job chale. parallel me na chale job dono saath me
    runs-on: VM-Runner     #runner ka kaam
    steps:
      - name: Get Code
        uses: actions/checkout@v5
    
      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
           node-version: 20
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy
        run: echo "Deploy Successful"                        # Abhi actual deply nahy kar rahe. bas print kar rahe hai