name: Deploy Dist          #Project ka naam
# on: [push, workflow_dispatch]    #kaha se trigger karna hai, manually trigger ho isliye workflow_dispatch likha hai
on:
  push:
    branches:
      - main
      - features/**
  workflow_dispatch:

jobs:
  Test:                   #job ka naam
    runs-on: VM-Runner     #runner ka kaam
    steps:
      # - name: Get Code     #local se runner me code copy kara raha hu
        # run: |
        #   echo "Cloning Repo.."
        #   echo "${{toJson(github)}}"         #Expression Context me code dalenge
        #   git clone https://github.com/${{github.repository}}.git
       
       - name: Get Code 
         uses: actions/checkout@v5                          #Local se vm me code copy ho jayega 
       - name: Install Node.js v20
         uses: actions/setup-node@v4                         #Node v20 install hoga
         with:
           node-version: 20
       - name: Print Node Version                            #Node ka version check karenge. Aapke Node install karna hoga aapke self Hosted runner me.
         run: node -v
       - name: Cache Dependencies
         uses: actions//cache@v4
         with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock-json')}}
       - name: Install Dependencies
         run: npm install                                   # "npm ci" bhi use kar skate hai automated env ke liye
       - name: Run Test Case                                # Run test Case from Package.json
         run: npm run test
  
  Build:
    needs: Test                                             #Test job complete hone ke baad ye Deploy job chale. parallel me na chale job dono saath me
    runs-on: Runner     #runner ka kaam
    steps:
      - name: Get Code
        uses: actions/checkout@v5 
      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
           node-version: 20
      - name: Cache Dependencies
        uses: actions//cache@v4
        with: 
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock-json') }}     #file ke basis par hum unique key create kar skate hai
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Download Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  Deploy:
    needs: Build                                             #Test job complete hone ke baad ye Deploy job chale. parallel me na chale job dono saath me
    runs-on: Runner     #runner ka kaam
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Deploy
        run: echo "Deploy Successful"                        # Abhi actual deply nahy kar rahe. bas print kar rahe hai